spring.mail.host=smtp.hostinger.com
spring.mail.port=587
spring.mail.username=noreply@cinecrewstaffing.com
spring.mail.password=Chakir00@
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=9075